name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: node common/scripts/install-run-rush.js change -v
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js rebuild --verbose
      - run: node common/scripts/install-run-rush.js test

      - run: bash <(curl -s https://codecov.io/bash) -f libraries/struct/coverage/lcov.info -F struct

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: apps/demo/lib
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
